version: "2"
services:
  app:
    build: ./app
    links:
      - db
      - redis
    ports:
      - "5000:5000"
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: database.conf
    volumes:
      - db_volume:/var/lib/postgresql
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  db_volume:
